AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Microservice architecture with pulse monitoring and range provider.

Globals:
  Function:
    Runtime: java17
    Architectures:
      - x86_64
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        LOGGER_LEVEL: FINEST
        BASE_URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/range"

Resources:

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  PulseAbnormalValuesStream:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse_abnormal_values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PulseJumpValuesStream:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse_jumps_values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PulseLastValues:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: last_pulse_values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  PulseValuesAnalyzer:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: pulse-values-analyzer
      Handler: telran.pulse.monitoring.App::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PulseAbnormalValuesStream
        - DynamoDBReadPolicy:
            TableName: pulse_values
      Events:
        TableRecordChange:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: arn:aws:dynamodb:us-east-1:692859932768:table/pulse_values/stream/2024-11-09T14:00:00.052
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'

  PulseJumpAnalyzer:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: pulse-jump-analyzer
      Handler: telran.pulse.monitoring.App::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PulseJumpValuesStream
        - DynamoDBCrudPolicy:
            TableName: !Ref PulseLastValues
        - DynamoDBReadPolicy:
            TableName: pulse_values
      Events:
        TableRecordChange:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: arn:aws:dynamodb:us-east-1:692859932768:table/pulse_values/stream/2024-11-09T14:00:00.052
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'

Outputs:

  ApiGatewayUrl:
    Description: "API Gateway URL for the range provider function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  PulseValuesAnalyzerFunctionArn:
    Description: "ARN of the pulse-values-analyzer function"
    Value: !GetAtt PulseValuesAnalyzer.Arn

  PulseJumpAnalyzerFunctionArn:
    Description: "ARN of the pulse-jump-analyzer function"
    Value: !GetAtt PulseJumpAnalyzer.Arn

  PulseAbnormalValuesStreamArn:
    Description: "ARN of the pulse_abnormal_values DynamoDB stream"
    Value: !GetAtt PulseAbnormalValuesStream.StreamArn