AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Microservice architecture with pulse monitoring and range provider.

Globals:
  Function:
    Runtime: java17
    Architectures:
      - x86_64
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        LOGGER_LEVEL: FINEST

Resources:

  PulseValuesStream:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse_values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PulseAbnormalValuesStream:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse_abnormal_values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE


  RangeProviderFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: range-provider
      Handler: helloworld.App::handleRequest
      MemorySize: 512
      Events:
        RangeProviderApi:
          Type: Api
          Properties:
            Path: /range
            Method: get

 
  PulseValuesAnalyzer:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: pulse-values-analyzer
      Handler: telran.pulse.monitoring.App::handleRequest
      Environment:
        Variables:
          API_GATEWAY_ID: !Ref ServerlessRestApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PulseAbnormalValuesStream
        - DynamoDBCrudPolicy:
            TableName: !Ref PulseValuesStream
      Events:
        TableRecordChange:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: !GetAtt PulseValuesStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'

Outputs:

  RangeProviderApiUrl:
    Description: "API Gateway URL for range provider function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/range"
  
 
  RangeProviderFunctionArn:
    Description: "ARN of the range-provider function"
    Value: !GetAtt RangeProviderFunction.Arn
  
  PulseValuesAnalyzerFunctionArn:
    Description: "ARN of the pulse-values-analyzer function"
    Value: !GetAtt PulseValuesAnalyzer.Arn
  

  PulseValuesStreamArn:
    Description: "ARN of the pulse_values DynamoDB stream"
    Value: !GetAtt PulseValuesStream.StreamArn
  
  PulseAbnormalValuesStreamArn:
    Description: "ARN of the pulse_abnormal_values DynamoDB stream"
    Value: !GetAtt PulseAbnormalValuesStream.StreamArn